[package]
name = "r-liv"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
image = "0.24.1"
vulkano = "0.29.0"
bytemuck = { version = "1.9.1", features = ["derive", "extern_crate_std", "min_const_generics"] }
vulkano-win = "0.29.0"
winit = "0.26"
