name: Rust

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Linux Release
          path: target/release/r-liv

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: ninja
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Windows Release
          path: target/release/r-liv.exe
